### ISSUE TITLE
How to move the RB_Vogui in a script

### ISSUE THREAD

**Issue by JamesKeegan1** [RobotnikAutomation/rbvogui_sim#2]
Hi all,

I am currently working on a project that involves the RB Vogui with a UR10 and am running into some issues while trying to understand the code. Firstly, I can't seem to get a moveit script to work that should automatically move the UR10 attached to the RB Vogui to a predetermined position in a python script. I was wondering if you knew all the move group identifiers required to make the arm work in a script. I've tried to replicate a script I had that just moves a UR10 by itself and it doesn't seem to work.
Secondly, I was curious to know if there was a RB Vogui movement function, where you can set a goal pose and have the machine drive to this location. I can't find any source files that would indicate that this is possible, yet I do see that there is a goal pose rostopic and was curious if I had missed something.
Any help with these issues would be massively appreciated.

Kind regards,
James

**Comment by JamesKeegan1** [comment]
any help guys??

**Comment by robert-ros** [comment]
The Robotnik's robots can be commanded through the standard ROS topics like actionlibs or move_base goals. So the question is more related to ROS than this repository. 

However, I have created a basic script to control de mobile base and the arm: [examples](https://github.com/RobotnikAutomation/rbvogui_sim/tree/e4b0a1c8bc904844994e7035c1d9ff19c8caaa41/rbvogui_gazebo/examples). 

I hope it helps!
