### ISSUE TITLE
gazebo gui crash on lauching simulation

### ISSUE THREAD

**Issue by Dkaka** [RobotnikAutomation/rbvogui_sim#4]
Hi Robert,

I'm trying out the simulation for the robot but couldn't got the gazebo gui. Looks like it's crashing on lauching.

(I followed the procedures for installing the dependencies. And confirmed that barebone gazebo works fine. And I tried both stable and the developer version)
However, it looks like the backend wokrs fine? I could use the teleop panel in Rviz to drive the robot and see the 2D laser points.

Here are the terminal outputs for bringing up  RB-Vogui: 

`roslaunch rbvogui_sim_bringup rbvogui_complete.launch robot_model:=rbvogui`

![Screenshot from 2021-11-26 13-26-03](https://user-images.githubusercontent.com/11716364/143588699-804e8d0a-b294-4a80-bcbe-864a25c6c5e7.png)
![Screenshot from 2021-11-26 13-25-22](https://user-images.githubusercontent.com/11716364/143588689-be0b25b4-f433-4e80-a5e5-672b31cc89cf.png)

![Screenshot from 2021-11-26 13-24-52](https://user-images.githubusercontent.com/11716364/143588670-9564dff3-4750-4005-9ebd-82d9cf6a7372.png)

**Comment by robert-ros** [comment]
Hi Ziwen!

I just tested the current repository (developer version) on a virtual machine with a fresh Ubuntu and ROS installation and it worked without problems.

From the pictures you've attached it seems that is a problem related to Gazebo, specifically the GPU. I would bet that it is a problem with the graphical drivers in you laptop.

This repository uses the GPU for the 2D and 3D lasers. Its performance is better than without GPU. Anyway, you can disable the GPU by setting the `use_gpu` parameter to false. Just add this parameter to the rbvogui model that you want.

For example, launch a simple rbvogui without GPU:

`roslaunch rbvogui_sim_bringup rbvogui_complete.launch robot_model:=rbvogui robot_xacro:=rbvogui_std.urdf.xacro use_gpu:=false
`

**Comment by Dkaka** [comment]
Hi Robert,

I guess you are right that this is a problem related to GPU. I tried the repository on a laptop with Intel integrated Graphics card and it works fine.

The previous issue was on a machine with an Nvidia Quadro card. I tried it again on an Nvidia Gefore card and the issue persisits. Perhaps you could try running it on a machine with an Nvidia GPU to reproduce the problem?

At the moment, I could restore gazebo_gui after it crashed by launching gzeclinet in a separate terminal with: 
`gzclient -V`  (`--verbose` also works)
However, the GUI is missing current states of simulation in the bottom, such as FPS.
![image](https://user-images.githubusercontent.com/11716364/145225808-5607fb8e-0812-45b0-bc9b-df9d33a63d4c.png)

**Comment by robert-ros** [comment]
Sorry I closed the issue accidentally. 

What happens if you delete the sensors of the robot? (benewake, lidar, imu and gps) You can do it by deleting the sensor parts in the [urdf of the robot]( https://github.com/RobotnikAutomation/rbvogui_common/blob/32cd39272cb5142db421801b6eb21a8dae370684/rbvogui_description/robots/rbvogui_std.urdf.xacro#L77) 

Furthermore, what happens if you launch a different world? For example:

`
roslaunch rbvogui_sim_bringup rbvogui_complete.launch world:=worlds/rbvogui.world
`

Finally, open a terminal and type `nvidia-settings`. Make sure that it works in Performance Mode:

![image](https://user-images.githubusercontent.com/59690050/153604663-1a7f5736-1bd8-4577-93e5-69ea7e0c773b.png)

**Comment by robert-ros** [comment]
Hi Ziwen!

This issue is fixed. For some reason Gazebo crashes when you have the following conditions

    - Gabezo version 9.0.0.
    - GPU enabled
    - A gazebo world with orthographic projection by default.

I have changed the default world to perspective projection, so the problem should not happen again.
