### ISSUE TITLE
vineyard.world load failed!

### ISSUE THREAD

**Issue by shmm91** [RobotnikAutomation/rbvogui_sim#8]
Thanks for your great work!
vineyard.world load failed, can't find the model.
[Err] [MeshShape.cc:60] No mesh specified
[Wrn] [FuelModelDatabase.cc:248] URI not supported by Fuel [model://vineyard0/meshes/Grape0_low.dae]
[Wrn] [SystemPaths.cc:464] File or path does not exist [""] [model://vineyard0/meshes/Grape0_low.dae]

**Comment by robert-ros** [comment]
Hi @shmm91!

Unfortunately, the vineyard.world is not supported yet. In the future we will add an outdoor scenario but at the moment we
are working on the internal urdf structure of the rbvogui.
